/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.doanjava.javaswing;

import com.doanjava.DAO.ConnectSQL;
import com.doanjava.DAO.ThucDonDAO;
import com.doanjava.DTO.ThucDon;
import com.doanjava.SERVICE.ThucDonSERVICE;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS
 */
public class QLThucDon extends javax.swing.JFrame {

    String filename = null;
    byte[] image = null;
    
    ThucDon thucDon;
    ThucDonDAO thucDonDAO;
    ThucDonSERVICE thucDonSERVICE;
    DefaultTableModel defaultTableModel;
    public Connection conn = ConnectSQL.getConnection();
    
    public void kichThuocAnh(){
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image image = img.getScaledInstance(lbImages.getWidth(), lbImages.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(image);
        lbImages.setIcon(icon);
    }
    
    public QLThucDon() {
        initComponents();
        loadLoaiMonAn();
        Disable();

        thucDon = new ThucDon();
        thucDonSERVICE = new ThucDonSERVICE();
        kichThuocAnh();
        
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) { 
                return false;
            }
        };
        
        tableFood.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã món");
        defaultTableModel.addColumn("Tên món");
        defaultTableModel.addColumn("Loại món");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Giá tiền");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Hình ảnh");
        
        setDataTable( thucDonSERVICE.getAllThucDon()); //để dữ liệu vào bảng
    }
    
    private void setDataTable(  List<ThucDon> thucDons ){ //lấy dữ liệu cho bảng
                for(ThucDon thucDon : thucDons){
            defaultTableModel.addRow(new Object[]{thucDon.getMaMonAn(),thucDon.getTenMonAn(),
                thucDon.getMaLoaiMon(),thucDon.getDonVi(),thucDon.getGiaTien(),thucDon.getSoLuong(),
                thucDon.getImageMonAn()});
        }
}

    public void Disable(){
        tfMaMon.setEnabled(false);
        tfTen.setEnabled(false);
        tfMaMon.setEnabled(false);
        tfDonVi.setEnabled(false);
        tfGia.setEnabled(false);
        tfSoLuong.setEnabled(false);
        btnThem.setEnabled(true);
        btnLuu.setEnabled(false);
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
    }
    
    public void Enable(){
        tfMaMon.setEnabled(true);
        tfTen.setEnabled(true);
        tfMaMon.setEnabled(true);
        tfDonVi.setEnabled(true);
        tfGia.setEnabled(true);
        tfSoLuong.setEnabled(true);
        btnThem.setEnabled(true);
        btnLuu.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
    }
    
    public void Remove(){
        tfMaMon.setText("");
        tfTen.setText("");
        tfMaMon.setText("");
        tfDonVi.setText("");
        tfGia.setText("");
        tfSoLuong.setText("");
    }
     
    public void Refesh(){
       defaultTableModel.setRowCount(0); //Xóa dữ liệu cũ về 0
       setDataTable( thucDonSERVICE.getAllThucDon()); // lấy dữ liệu mới
    }
    
     private void loadLoaiMonAn() {
        String sql = " SELECT * FROM DanhMucMon WHERE maLoai = maLoai";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                this.cbLoaiMon.addItem(rs.getString("maLoai"));
            }
            } catch(Exception e){

            }
          }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpanelTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelThucDon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelDatBan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelDoanhThu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelDSBan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelThongTin = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbThoat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFood = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbThongtin = new javax.swing.JLabel();
        lbMatu = new javax.swing.JLabel();
        lbLoai = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        tfGia = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfDonVi = new javax.swing.JTextField();
        tfTen = new javax.swing.JTextField();
        cbLoaiMon = new javax.swing.JComboBox<>();
        tfMaMon = new javax.swing.JTextField();
        tfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lbGia1 = new javax.swing.JLabel();
        tfTenLoai = new javax.swing.JTextField();
        lbThongtin1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        tfLink = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lbImages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1050, 630));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1101, 607));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelTrangChu.setBackground(new java.awt.Color(51, 51, 51));
        jpanelTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelTrangChuMouseClicked(evt);
            }
        });
        jpanelTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/home23px.png"))); // NOI18N
        jpanelTrangChu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trang chủ");
        jpanelTrangChu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(jpanelTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 50));

        panelThucDon.setBackground(new java.awt.Color(51, 51, 51));
        panelThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelThucDonMouseClicked(evt);
            }
        });
        panelThucDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/Menu_23px.png"))); // NOI18N
        panelThucDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        panelThucDon.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thực đơn");
        panelThucDon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jLabel2.setBackground(new java.awt.Color(49, 139, 130));
        jLabel2.setOpaque(true);
        panelThucDon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jPanel2.add(panelThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 50));

        panelDatBan.setBackground(new java.awt.Color(51, 51, 51));
        panelDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDatBanMouseClicked(evt);
            }
        });
        panelDatBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/table_23px.png"))); // NOI18N
        panelDatBan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel8.setBackground(new java.awt.Color(153, 0, 0));
        panelDatBan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Đặt bàn");
        panelDatBan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(panelDatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 50));

        panelHoaDon.setBackground(new java.awt.Color(51, 51, 51));
        panelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHoaDonMouseClicked(evt);
            }
        });
        panelHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/bills_23px.png"))); // NOI18N
        panelHoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel11.setBackground(new java.awt.Color(153, 0, 0));
        panelHoaDon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hóa đơn");
        panelHoaDon.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(panelHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 50));

        panelDoanhThu.setBackground(new java.awt.Color(51, 51, 51));
        panelDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDoanhThuMouseClicked(evt);
            }
        });
        panelDoanhThu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/Money_23px.png"))); // NOI18N
        panelDoanhThu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel17.setBackground(new java.awt.Color(153, 0, 0));
        panelDoanhThu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Doanh thu");
        panelDoanhThu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(panelDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, 50));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/management_23px.png"))); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nhân viên");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 180, 50));

        panelDSBan.setBackground(new java.awt.Color(51, 51, 51));
        panelDSBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDSBanMouseClicked(evt);
            }
        });
        panelDSBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/table_23px.png"))); // NOI18N
        panelDSBan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DS Bàn");
        panelDSBan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(panelDSBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 50));

        panelThongTin.setBackground(new java.awt.Color(51, 51, 51));
        panelThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelThongTinMouseClicked(evt);
            }
        });
        panelThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/info_24px.png"))); // NOI18N
        panelThongTin.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Thông tin");
        panelThongTin.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jPanel2.add(panelThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        lbThoat.setBackground(new java.awt.Color(49, 139, 130));
        lbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/Close_18px.png"))); // NOI18N
        lbThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThoatMouseClicked(evt);
            }
        });

        tableFood.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableFood.setForeground(new java.awt.Color(49, 139, 130));
        tableFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã món ăn", "Loại món ăn", "Tên món ăn", "Số lượng", "Đơn vị tính", "Giá bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableFood.setSelectionForeground(new java.awt.Color(49, 139, 130));
        tableFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFoodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFood);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbThongtin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThongtin.setForeground(new java.awt.Color(49, 139, 130));
        lbThongtin.setText("Thông tin món:");
        lbThongtin.setToolTipText("");

        lbMatu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMatu.setForeground(new java.awt.Color(49, 139, 130));
        lbMatu.setText("Mã món:");
        lbMatu.setToolTipText("");

        lbLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLoai.setForeground(new java.awt.Color(49, 139, 130));
        lbLoai.setText("Mã loại món:");
        lbLoai.setToolTipText("");

        lbTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTen.setForeground(new java.awt.Color(49, 139, 130));
        lbTen.setText("Tên món:");
        lbTen.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(49, 139, 130));
        jLabel20.setText("Đơn vị tính:");
        jLabel20.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(49, 139, 130));
        jLabel22.setText("Số lượng:");
        jLabel22.setToolTipText("");

        lbGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia.setForeground(new java.awt.Color(49, 139, 130));
        lbGia.setText("Giá tiền:");
        lbGia.setToolTipText("");

        tfGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfGia.setForeground(new java.awt.Color(49, 139, 130));
        tfGia.setToolTipText("");
        tfGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfGiaKeyReleased(evt);
            }
        });

        tfSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSoLuong.setForeground(new java.awt.Color(49, 139, 130));
        tfSoLuong.setToolTipText("");
        tfSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSoLuongKeyReleased(evt);
            }
        });

        tfDonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDonVi.setForeground(new java.awt.Color(49, 139, 130));
        tfDonVi.setToolTipText("");

        tfTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTen.setForeground(new java.awt.Color(49, 139, 130));
        tfTen.setToolTipText("");

        cbLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLoaiMon.setForeground(new java.awt.Color(49, 139, 130));
        cbLoaiMon.setToolTipText("");
        cbLoaiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiMonActionPerformed(evt);
            }
        });

        tfMaMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfMaMon.setForeground(new java.awt.Color(49, 139, 130));
        tfMaMon.setToolTipText("");

        tfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTimKiem.setForeground(new java.awt.Color(49, 139, 130));
        tfTimKiem.setToolTipText("");
        tfTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTimKiemKeyReleased(evt);
            }
        });

        btnTimKiem.setForeground(new java.awt.Color(49, 139, 130));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/search_18px.png"))); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTimKiem.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        lbGia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbGia1.setForeground(new java.awt.Color(49, 139, 130));
        lbGia1.setText("Tên loại:");
        lbGia1.setToolTipText("");

        tfTenLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfTenLoai.setForeground(new java.awt.Color(49, 139, 130));
        tfTenLoai.setToolTipText("");
        tfTenLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTenLoaiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfSoLuong)
                                    .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMaMon)
                                    .addComponent(tfTen)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbLoai)
                                .addGap(18, 18, 18)
                                .addComponent(cbLoaiMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfDonVi))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbThongtin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMaMon, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTen)
                    .addComponent(lbTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbGia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDonVi)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfGia, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(lbGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lbThongtin1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbThongtin1.setForeground(new java.awt.Color(49, 139, 130));
        lbThongtin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongtin1.setText("Quản lý món ăn");
        lbThongtin1.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setForeground(new java.awt.Color(49, 139, 130));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/save_28px.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfLink.setForeground(new java.awt.Color(255, 255, 255));
        tfLink.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImages.setForeground(new java.awt.Color(49, 139, 130));
        lbImages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/doanjava/javaswing/IMG/ios_photos_100px.png"))); // NOI18N
        lbImages.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbImages.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbImages.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImagesMouseClicked(evt);
            }
        });
        jPanel6.add(lbImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 190, 190));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThongtin1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(lbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbThongtin1)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpanelTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelTrangChuMouseClicked
        TrangChinh home = new TrangChinh();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_jpanelTrangChuMouseClicked

    private void panelThucDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThucDonMouseClicked
        QLThucDon qlmonan = new QLThucDon();
        this.setVisible(false);
        qlmonan.setVisible(true);
    }//GEN-LAST:event_panelThucDonMouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        QLNhanVien qlnhanvien = new QLNhanVien();
        this.setVisible(false);
        qlnhanvien.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void lbThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThoatMouseClicked
        int click=JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát chương trình hay không?", "Thông báo", 2);
        if(click==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_lbThoatMouseClicked

    private void panelDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDoanhThuMouseClicked
        QLDoanhThu qldoanhthu = new QLDoanhThu();
        this.setVisible(false);
        qldoanhthu.setVisible(true);
    }//GEN-LAST:event_panelDoanhThuMouseClicked

    private void panelDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDatBanMouseClicked
        QLDatBan qldatban = new QLDatBan();
        this.setVisible(false);
        qldatban.setVisible(true);
    }//GEN-LAST:event_panelDatBanMouseClicked

    private void tableFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFoodMouseClicked
        cbLoaiMon.removeAllItems();
        int click=tableFood.getSelectedRow();
        TableModel model=tableFood.getModel();

        tfMaMon.setText(model.getValueAt(click, 0).toString());
        tfTen.setText(model.getValueAt(click, 1).toString());
        cbLoaiMon.addItem(model.getValueAt(click, 2).toString());
        tfDonVi.setText(model.getValueAt(click, 3).toString());
        String []s1=model.getValueAt(click,4).toString().split("\\s");
        tfGia.setText(s1[0]);
        tfSoLuong.setText(model.getValueAt(click, 5).toString());
        
        tfLink.setText(model.getValueAt(click,6).toString());
        ImageIcon icon = new ImageIcon(new ImageIcon(model.getValueAt(click,6).toString()).getImage().getScaledInstance(lbImages.getWidth(), lbImages.getHeight(), Image.SCALE_SMOOTH));
        lbImages.setIcon(icon);
        
//        byte[] img = (thucDonSERVICE.getAllThucDon().get(click).getImageMonAn());
//        ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbImages.getWidth(), lbImages.getHeight(), Image.SCALE_SMOOTH));
//        lbImages.setIcon(imgIcon);
        
        //tfGia.setText(model.getValueAt(click, 5).toString());

        tfMaMon.setEnabled(false);
        this.btnThem.setEnabled(true);
        this.btnSua.setEnabled(true);
        this.btnXoa.setEnabled(true);
    }//GEN-LAST:event_tableFoodMouseClicked

    private void tfSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSoLuongKeyReleased

    }//GEN-LAST:event_tfSoLuongKeyReleased

    private void tfGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGiaKeyReleased

    }//GEN-LAST:event_tfGiaKeyReleased

    private void panelHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHoaDonMouseClicked
        QLHoaDon hoadon = new QLHoaDon();
        this.setVisible(false);
        hoadon.setVisible(true);
    }//GEN-LAST:event_panelHoaDonMouseClicked

    private void panelDSBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDSBanMouseClicked
        QLDSBan qldatban = new QLDSBan();
        this.setVisible(false);
        qldatban.setVisible(true);
    }//GEN-LAST:event_panelDSBanMouseClicked

    private void panelThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelThongTinMouseClicked
        QLThongTin thongtin = new QLThongTin();
        this.setVisible(false);
        thongtin.setVisible(true);
    }//GEN-LAST:event_panelThongTinMouseClicked

    private void tfTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTimKiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemKeyReleased

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tableFood.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(QLThucDon.this, "Vui lòng chọn bàn cần xóa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            int xacNhan = JOptionPane.showConfirmDialog(QLThucDon.this, "Bạn có chắc chắn muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION);
            if(xacNhan == JOptionPane.YES_OPTION){
                String maMonAn = String.valueOf(tableFood.getValueAt(row, 0));
                thucDonSERVICE.xoaThucDon(maMonAn);
            }
        }
        Refesh();
    }//GEN-LAST:event_btnXoaActionPerformed
    
    private void timkiemMonAn(String query){
           TableRowSorter<DefaultTableModel> tbl = new TableRowSorter<DefaultTableModel>(defaultTableModel);
           tableFood.setRowSorter(tbl);
           tbl.setRowFilter(RowFilter.regexFilter(query));
    }
           
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String query = tfTimKiem.getText();
        timkiemMonAn(query);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Enable();
        Remove();
        cbLoaiMon.removeAllItems();
            loadLoaiMonAn();
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private boolean kiemtraNull(){
        if(tfMaMon.getText().equals("")){
            JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa nhập mã món ăn!");
            return false;
        }
        else
        if(tfTen.getText().equals("")){
            JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa nhập tên món ăn!");
            return false;
        }
        else
        if(tfDonVi.getText().equals("")){
            JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa nhập đơn vị tính!");
            return false;
        }
        else   
        if(tfSoLuong.getText().equals("")){
            JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa nhập số lượng món ăn!");
            return false;
        }
        else
        if(cbLoaiMon.getSelectedItem().equals("")){
           JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa chọn loại món ăn!");
            return false;
        }
        else{ 
        if(tfGia.getText().equals("")){
            JOptionPane.showMessageDialog(QLThucDon.this,"Bạn chưa nhập giá tiền!");
            return false;
        }
        else{ 
            return true;
        }
        }
    }
    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(kiemtraNull()){
        thucDon.setMaMonAn(tfMaMon.getText());                            
        thucDon.setTenMonAn(tfTen.getText());              
        thucDon.setMaLoaiMon(cbLoaiMon.getSelectedItem().toString());              
        thucDon.setDonVi(tfDonVi.getText());         
        thucDon.setGiaTien(Float.valueOf(tfGia.getText()));                 
        thucDon.setSoLuong(Integer.parseInt(tfSoLuong.getText()));   
        thucDon.setImageMonAn(tfLink.getText()); 
        
        thucDonSERVICE.themThucDon(thucDon);
            JOptionPane.showMessageDialog(null, "Đã thêm món ăn mới thành công!^^");
        Refesh();}
    }//GEN-LAST:event_btnLuuActionPerformed

    private void cbLoaiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiMonActionPerformed
       String sql = "SELECT tenLoai FROM DanhMucMon WHERE maLoai = ?";
        try{
            String maTheLoaiString = (String) cbLoaiMon.getSelectedItem();
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, maTheLoaiString);
            ResultSet rs = preparedStatement.executeQuery();
            if(rs.next()){
                tfTenLoai.setText(rs.getString("tenLoai"));
            }
        } catch(Exception e){

        }
    }//GEN-LAST:event_cbLoaiMonActionPerformed

    private void tfTenLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTenLoaiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenLoaiKeyReleased

    private void lbImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImagesMouseClicked
         JFileChooser open = new JFileChooser("E:\\IT\\JavaSwing\\DoAnJava\\JavaSwing\\src\\com\\doanjava\\javaswing\\IMG\\FoodPNG");
        open.setDialogTitle("Chọn ảnh");
        int file=open.showOpenDialog(null);
        if(file==JFileChooser.APPROVE_OPTION){
            tfLink.setText(open.getCurrentDirectory().toString()+"\\"+open.getSelectedFile().getName());
            ImageIcon icon = new ImageIcon(tfLink.getText());
            lbImages.setIcon(icon);
            //Chinh kich thuoc hinh anh fit voi jlabel
            Image img = icon.getImage().getScaledInstance(lbImages.getWidth(), lbImages.getHeight(),Image.SCALE_SMOOTH);
            lbImages.setIcon(new ImageIcon(img));
        }
        else JOptionPane.showMessageDialog(QLThucDon.this, "Chưa chọn đường dẫn tới ảnh!!");
    }//GEN-LAST:event_lbImagesMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        btnLuu.setEnabled(true);
        tfMaMon.setEnabled(false);
        int row = tableFood.getSelectedRow();   
        if(row == -1){
            JOptionPane.showMessageDialog(QLThucDon.this, "Vui lòng chọn bàn cần sửa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            int xacNhan = JOptionPane.showConfirmDialog(QLThucDon.this, "Bạn có chắc chắn muốn sửa không?","Thông báo",JOptionPane.YES_NO_OPTION);
            if(xacNhan == JOptionPane.YES_OPTION){
                
            thucDon.setMaMonAn(tfMaMon.getText());
            thucDon.setTenMonAn(tfTen.getText());
            thucDon.setMaLoaiMon(cbLoaiMon.getItemAt(cbLoaiMon.getSelectedIndex()));
            thucDon.setDonVi(tfDonVi.getText());   
            thucDon.setGiaTien(Float.valueOf(tfGia.getText()));       
            thucDon.setSoLuong(Integer.parseInt(tfSoLuong.getText()));   
            thucDon.setImageMonAn(tfLink.getText()); 
            
               // String maBan = String.valueOf(tableNV.getValueAt(row, 0));
                thucDonSERVICE.suaThucDon(thucDon);
            JOptionPane.showMessageDialog(null, "Đã sửa thông tin món ăn thành công!^^");
                Refesh();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLThucDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelTrangChu;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGia1;
    private javax.swing.JLabel lbImages;
    private javax.swing.JLabel lbLoai;
    private javax.swing.JLabel lbMatu;
    private javax.swing.JLabel lbTen;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JLabel lbThongtin;
    private javax.swing.JLabel lbThongtin1;
    private javax.swing.JPanel panelDSBan;
    private javax.swing.JPanel panelDatBan;
    private javax.swing.JPanel panelDoanhThu;
    private javax.swing.JPanel panelHoaDon;
    private javax.swing.JPanel panelThongTin;
    private javax.swing.JPanel panelThucDon;
    private javax.swing.JTable tableFood;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfMaMon;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTenLoai;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables

}
